### ISSUE TITLE
Ubuntu 16.04 problem with matlab-kernel and jupyter

### ISSUE THREAD

**Issue by ouboub** [nnicandro/emacs-jupyter#359]
Some weeks ago I could use ob-ipython with the matlab-kernel of Matlab 2019a and python3.5.
In Ubuntu 16.04.
Not any longer.
Since ob-ipython is not supported anymore I switched to emacs-jupyter and run into a, most likely similar problem.

Matlab 2019a is the latest version compatible with python 3.5
here is what I did 

-   install the matlab engine
```
cd usr/local/MATLAB/R2019a/extern/engines/python
sudo python3.5 setup.py install
```
-   install jupyter etc
```
sudo apt-get install python3-setuptools
sudo -H python3 -m pip install jupyter
sudo apt-get remove python3-pexpect
sudo -H python3 -m pip install pexpect
sudo -H python3 -m pip install matlab<sub>kernel</sub>
```
-   start the matlab engine
```
/usr/bin/python3
```
```
import matlab.engine
eng = matlab.engine.start<sub>matlab</sub>()
```
-   install emacs-jupyter via the package system.
-   add jupyter to org-babel-load-languages.
```
(org-babel-do-load-languages
 'org-babel-load-languages
 '((R . t)
   (emacs-lisp . t)
   (octave . t)
   (python . t)
   (jupyter . t)))    ;problem
```
-   run eval-last-sexep

The following error pops up
```
Debugger entered&#x2013;Lisp error: (file-missing "Searching for program" "No such file or directory" "jupyter")
  call-process("jupyter" nil t nil "kernelspec" "list" "&#x2013;json")
  apply(call-process "jupyter" nil t nil ("kernelspec" "list" "&#x2013;json"))
  process-file("jupyter" nil t nil "kernelspec" "list" "&#x2013;json")
  apply(process-file "jupyter" nil t nil ("kernelspec" "list" "&#x2013;json"))
  jupyter-command("kernelspec" "list" "&#x2013;json")
  jupyter-available-kernelspecs(nil)
  org-babel-jupyter-aliases-from-kernelspecs()
  byte-code("\\300 \\210\\301\\302\\303\\"\\210\\301\\304\\305\\"\\210\\306\\307!\\207"
  [org-babel-jupyter-aliases-from-kernelspecs add-hook
  org-export-before-processing-hook org-babel-jupyter-setup-export org-export-before-parsing-hook org-babel-jupyter-strip-ansi-escapes
  provide ob-jupyter] 3)   
  require(ob-jupyter)
  org-babel-do-load-languages(org-babel-load-languages ((R . t) (ditaa . t) (dot . t) (emacs-lisp . t)
  (gnuplot . t) (haskell) (latex . t) (ledger . t) (ocaml) (octave . t)
  (python . t) (ruby . t) (screen) (sql) (sqlite . t) (jupyter . t)))
  eval((org-babel-do-load-languages 'org-babel-load-languages '((R . t)
  (ditaa . t) (dot . t) (emacs-lisp . t) (gnuplot . t) (haskell) (latex . t)
  (ledger . t) (ocaml) (octave . t) (python . t) (ruby . t) (screen) (sql) (sqlite . t) (jupyter . t))) nil)
  elisp&#x2013;eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```
-   in /usr/local/bin

I have

```
jupyter-bundlerextension
jupyter-console
jupyter-nbconvert
jupyter-nbextension
jupyter-notebook
jupyter-qtconsole
jupyter-serverextension
jupyter-trust
```
But no jupyter!

I tried to use pip again and again to install it, but no script jupyter is installed.
I am deeply pluzzled!

regards

Uwe Brauer

**Comment by ouboub** [comment]
I think I solved it (almost) it was quite an ordeal, I have to say
here is what I did 

# reinstall jupyter
```
sudo dpkg --purge python3-ptyprocess
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir jupyter
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir numpy
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir pymatbridge
sudo -H pip3 install &#x2013;upgrade &#x2013;force-reinstall &#x2013;no-cache-dir matlab<sub>kernel</sub>
```

# check <https://github.com/Calysto/matlab_kernel#kernel-times-out-while-starting>
```
python3 -m matlab_kernel.check 
```
That told me to look for a matlab solution


# matlab solution for Ubuntu 16.04

<https://de.mathworks.com/matlabcentral/answers/403561-import-error-matlab-engine-in-python>


## solve the gcc library problem
```
LD<sub>LIBRARY</sub><sub>PATH</sub>=/usr/local/lib64/:$LD<sub>LIBRARY</sub><sub>PATH</sub>
$ export LD<sub>LIBRARY</sub><sub>PATH</sub>
$ sudo apt-add-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-6 g++-6
```

## install the engine again
```
cd usr/local/MATLAB/R2019a/extern/engines/python
sudo /usr/bin/python3 setup.py install
```

## Start the engine
 now it works, however 
```jupyter --kernel matlab
```
still gives
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-matlab` not found.
```
but I can live with that
if somebody can tell me about the last error it would be nice but then it works for me (for the moment) so it be ok to close the issue, but then I am not sure

**Comment by nnicandro** [comment]
I'm not seeing the command that you entered which gives you the ```Jupyter command `jupyter-matlab` not found``` exception. The code after `now it works, however` is empty. Can you edit your post to show the command.

**Comment by ouboub** [comment]
Hi

I was able to solve the issue at the weekend, and it was a considerable ordeal, I have to admit


# reinstall jupyter
```
sudo dpkg --purge python3-ptyprocess
sudo -H pip3 install --upgrade --force-reinstall --no-cache-dir jupyter
sudo -H pip3 install --upgrade --force-reinstall --no-cache-dir numpy
sudo -H pip3 install --upgrade --force-reinstall --no-cache-dir pymatbridge
sudo -H pip3 install --upgrade --force-reinstall --no-cache-dir matlab_kernel
```

# check <https://github.com/Calysto/matlab_kernel#kernel-times-out-while-starting>
```
  python3 -m matlab_kernel.check 
```
That told me to look for a matlab solution


# matlab solution for Ubuntu 16.04

<https://de.mathworks.com/matlabcentral/answers/403561-import-error-matlab-engine-in-python>


## solve the gcc library problem
```
LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
$ export LD_LIBRARY_PATH
$ sudo apt-add-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-6 g++-6
```



## install the engine again
```
cd *usr/local/MATLAB/R2019a/extern/engines/python*
sudo /usr/bin/python3 setup.py install
```

## Start the engine

regards

Uwe
